server:
  port: 8081

spring:
  application:
    name: identity-employee-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/identity_db}
    username: ${SPRING_DATASOURCE_USERNAME:reservation}
    password: ${SPRING_DATASOURCE_PASSWORD:reservation}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
