sonar.projectKey=room-reservation-system
sonar.projectName=Room Reservation System
sonar.sourceEncoding=UTF-8
sonar.sources=identity-employee-service/src/main,room-service/src/main,reservation-service/src/main,notification-audit-service/src/main,api-gateway/src/main,frontend/src
sonar.tests=identity-employee-service/src/test,room-service/src/test,reservation-service/src/test,notification-audit-service/src/test,api-gateway/src/test
sonar.java.binaries=identity-employee-service/target/classes,room-service/target/classes,reservation-service/target/classes,notification-audit-service/target/classes,api-gateway/target/classes
