server:
  port: 8082

spring:
  application:
    name: room-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/room_db}
    username: ${SPRING_DATASOURCE_USERNAME:reservation}
    password: ${SPRING_DATASOURCE_PASSWORD:reservation}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info
